package com.idet.pos.service;

import com.idet.pos.dto.CustomerDTO;
import com.idet.pos.dto.CustomerPurchaseStatsDTO;
import com.idet.pos.entity.Customer;
import com.idet.pos.exception.InvalidRequestException;
import com.idet.pos.exception.ResourceNotFoundException;
import com.idet.pos.projection.CustomerPurchaseStatsProjection;
import com.idet.pos.repository.CustomerRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

/**
 * CustomerService - Business Logic Layer
 * Handles all customer-related operations using Spring Data JPA.
 * Hibernate handles CRUD operations and transaction management automatically.
 */
@Service
@Transactional
public class CustomerService {

    private static final Logger logger = Logger.getLogger(CustomerService.class.getName());

    @Autowired
    private CustomerRepository customerRepository;

    /**
     * Save a new customer
     * Customer ID is expected to be set in the DTO (auto-generated by the frontend/controller)
     */
    public CustomerDTO saveCustomer(CustomerDTO dto) {
        logger.info("Service: Saving customer: " + dto.getName());
        if (dto.getId() == null || dto.getId().isEmpty()) {
            throw new InvalidRequestException("Customer ID is required");
        }
        if (customerRepository.existsById(dto.getId())) {
            throw new InvalidRequestException("Customer already exists: " + dto.getId());
        }
        Customer entity = new Customer(
                dto.getId(), dto.getName(), dto.getAddress(), dto.getEmail());
        Customer saved = customerRepository.save(entity);
        logger.info("Service: Customer saved successfully with ID: " + saved.getId());
        return new CustomerDTO(saved.getId(), saved.getName(), saved.getAddress(), saved.getEmail());
    }

    /**
     * Update an existing customer
     */
    public CustomerDTO updateCustomer(CustomerDTO dto) {
        logger.info("Service: Updating customer: " + dto.getId());
        if (!customerRepository.existsById(dto.getId())) {
            throw new ResourceNotFoundException("Customer not found: " + dto.getId());
        }
        Customer entity = new Customer(
                dto.getId(), dto.getName(), dto.getAddress(), dto.getEmail());
        Customer updated = customerRepository.save(entity);
        logger.info("Service: Customer updated successfully: " + dto.getId());
        return new CustomerDTO(updated.getId(), updated.getName(), updated.getAddress(), updated.getEmail());
    }

    /**
     * Delete a customer by ID
     */
    public void deleteCustomer(String id) {
        logger.info("Service: Deleting customer: " + id);
        if (!customerRepository.existsById(id)) {
            throw new ResourceNotFoundException("Customer not found: " + id);
        }
        customerRepository.deleteById(id);
        logger.info("Service: Customer deleted successfully: " + id);
    }

    /**
     * Find a customer by ID
     */
    @Transactional(readOnly = true)
    public CustomerDTO findCustomer(String id) {
        return customerRepository.findById(id)
                .map(entity -> new CustomerDTO(entity.getId(), entity.getName(), entity.getAddress(), entity.getEmail()))
                .orElseThrow(() -> new ResourceNotFoundException("Customer not found: " + id));
    }

    /**
     * Find all customers
     */
    @Transactional(readOnly = true)
    public List<CustomerDTO> findAllCustomers() {
        logger.info("Service: Fetching all customers");
        List<CustomerDTO> dtos = new ArrayList<>();
        for (Customer entity : customerRepository.findAll()) {
            dtos.add(new CustomerDTO(entity.getId(), entity.getName(), entity.getAddress(), entity.getEmail()));
        }
        return dtos;
    }

    @Transactional(readOnly = true)
    public List<CustomerPurchaseStatsProjection> findCustomerPurchaseStats() {
        return customerRepository.findCustomerPurchaseStats();
    }

    @Transactional(readOnly = true)
    public List<CustomerPurchaseStatsDTO> findCustomerPurchaseStatsDto() {
        return customerRepository.findCustomerPurchaseStatsDto();
    }

    @Transactional(readOnly = true)
    public List<CustomerDTO> searchCustomersByName(String namePart) {
        List<CustomerDTO> dtos = new ArrayList<>();
        for (Customer entity : customerRepository.findByNameContainingIgnoreCase(namePart)) {
            dtos.add(new CustomerDTO(entity.getId(), entity.getName(), entity.getAddress(), entity.getEmail()));
        }
        return dtos;
    }

    @Transactional(readOnly = true)
    public CustomerDTO findCustomerByEmail(String email) {
        Customer customer = customerRepository.findByEmailIgnoreCase(email)
                .orElseThrow(() -> new ResourceNotFoundException("Customer not found with email: " + email));
        return new CustomerDTO(customer.getId(), customer.getName(), customer.getAddress(), customer.getEmail());
    }
}

