package com.idet.pos.service;

import com.idet.pos.dto.ItemDTO;
import com.idet.pos.entity.Inventory;
import com.idet.pos.entity.Item;
import com.idet.pos.exception.ResourceNotFoundException;
import com.idet.pos.repository.InventoryRepository;
import com.idet.pos.repository.ItemRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

/**
 * ItemService - Business Logic Layer
 * Handles all item/product-related operations using Spring Data JPA.
 * Hibernate handles CRUD operations and transaction management automatically.
 */
@Service
@Transactional
public class ItemService {

    private static final Logger logger = Logger.getLogger(ItemService.class.getName());

    @Autowired
    private ItemRepository itemRepository;

    @Autowired
    private InventoryRepository inventoryRepository;

    /**
     * Save a new item
     * Item code is expected to be set in the DTO (auto-generated by the frontend/controller)
     */
    public ItemDTO saveItem(ItemDTO dto) {
        logger.info("Service: Saving item: " + dto.getDescription());
        Item entity = new Item(
                dto.getCode(), dto.getDescription(), dto.getUnitPrice());
        Item saved = itemRepository.save(entity);

        // Keep item + inventory creation in one transaction to avoid orphan item rows.
        if (!inventoryRepository.existsById(saved.getCode())) {
            Inventory inventory = new Inventory(saved.getCode(), 0, saved);
            inventoryRepository.save(inventory);
        }

        logger.info("Service: Item saved successfully with code: " + saved.getCode());
        return new ItemDTO(saved.getCode(), saved.getDescription(), saved.getUnitPrice());
    }

    /**
     * Update an existing item
     */
    public ItemDTO updateItem(ItemDTO dto) {
        logger.info("Service: Updating item: " + dto.getCode());
        Item entity = itemRepository.findById(dto.getCode())
                .orElseThrow(() -> new ResourceNotFoundException("Item not found: " + dto.getCode()));

        entity.setDescription(dto.getDescription());
        entity.setUnitPrice(dto.getUnitPrice());
        Item updated = itemRepository.save(entity);
        logger.info("Service: Item updated successfully: " + dto.getCode());
        return new ItemDTO(updated.getCode(), updated.getDescription(), updated.getUnitPrice());
    }

    /**
     * Delete an item by code
     */
    public void deleteItem(String code) {
        logger.info("Service: Deleting item: " + code);
        if (!itemRepository.existsById(code)) {
            throw new ResourceNotFoundException("Item not found: " + code);
        }

        // Delete child row first to keep referential integrity explicit.
        if (inventoryRepository.existsById(code)) {
            inventoryRepository.deleteById(code);
        }
        itemRepository.deleteById(code);
        logger.info("Service: Item deleted successfully: " + code);
    }

    /**
     * Find an item by code
     */
    @Transactional(readOnly = true)
    public ItemDTO findItem(String code) {
        return itemRepository.findById(code)
                .map(entity -> new ItemDTO(entity.getCode(), entity.getDescription(), entity.getUnitPrice()))
                .orElseThrow(() -> new ResourceNotFoundException("Item not found: " + code));
    }

    /**
     * Find all items
     */
    @Transactional(readOnly = true)
    public List<ItemDTO> findAllItems() {
        logger.info("Service: Fetching all items");
        List<ItemDTO> dtos = new ArrayList<>();
        for (Item entity : itemRepository.findAll()) {
            dtos.add(new ItemDTO(entity.getCode(), entity.getDescription(), entity.getUnitPrice()));
        }
        return dtos;
    }

    @Transactional(readOnly = true)
    public List<ItemDTO> searchItemsByDescription(String keyword) {
        List<ItemDTO> dtos = new ArrayList<>();
        for (Item entity : itemRepository.findByDescriptionContainingIgnoreCase(keyword)) {
            dtos.add(new ItemDTO(entity.getCode(), entity.getDescription(), entity.getUnitPrice()));
        }
        return dtos;
    }

    @Transactional(readOnly = true)
    public List<ItemDTO> findItemsByMinPrice(double minPrice) {
        List<ItemDTO> dtos = new ArrayList<>();
        for (Item entity : itemRepository.findByUnitPriceGreaterThanEqual(minPrice)) {
            dtos.add(new ItemDTO(entity.getCode(), entity.getDescription(), entity.getUnitPrice()));
        }
        return dtos;
    }
}

